# Generated by Django 2.2.5 on 2020-05-15 23:51

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('develop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WakeTownship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid', models.IntegerField()),
                ('ftr_code', models.IntegerField()),
                ('township', models.IntegerField()),
                ('name', models.CharField(max_length=14)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
