# Generated by Django 2.2.5 on 2020-05-18 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('develop', '0005_auto_20200517_2045'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WakeTownship',
        ),
    ]
