# Generated by Django 2.2.12 on 2020-05-25 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('develop', '0008_developmentplan_historicaldevelopmentplan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Development',
        ),
        migrations.DeleteModel(
            name='HistoricalDevelopment',
        ),
    ]
