# Generated by Django 2.2.12 on 2020-05-26 20:12

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('develop', '0009_auto_20200525_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developmentplan',
            name='acreage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='developmentplan',
            name='appealperi',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='developmentplan',
            name='approved',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='developmentplan',
            name='cac',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='developmentplan',
            name='creationda',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='developmentplan',
            name='creator',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='developmentplan',
            name='daystoappr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='developmentplan',
            name='developer',
            field=models.CharField(blank=True, max_length=48, null=True),
        ),
        migrations.AlterField(
            model_name='developmentplan',
            name='developer_field',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='developmentplan',
            name='devplan_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='developmentplan',
            name='editdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='developmentplan',
            name='editor',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='developmentplan',
            name='engineer',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='developmentplan',
            name='engineer_p',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='developmentplan',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='developmentplan',
            name='lots_apprv',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='developmentplan',
            name='lots_rec',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='developmentplan',
            name='lots_req',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='developmentplan',
            name='major_stre',
            field=models.CharField(blank=True, max_length=31, null=True),
        ),
        migrations.AlterField(
            model_name='developmentplan',
            name='plan_name',
            field=models.CharField(blank=True, max_length=44, null=True),
        ),
        migrations.AlterField(
            model_name='developmentplan',
            name='plan_numbe',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='developmentplan',
            name='plan_type',
            field=models.CharField(blank=True, max_length=39, null=True),
        ),
        migrations.AlterField(
            model_name='developmentplan',
            name='planner',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='developmentplan',
            name='planurl',
            field=models.CharField(blank=True, max_length=107, null=True),
        ),
        migrations.AlterField(
            model_name='developmentplan',
            name='planurl_ap',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='developmentplan',
            name='sq_ft_req',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='developmentplan',
            name='status',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='developmentplan',
            name='submitted',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='developmentplan',
            name='submitted_field',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='developmentplan',
            name='sunset_dat',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='developmentplan',
            name='units_appr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='developmentplan',
            name='units_req',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='developmentplan',
            name='updated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='developmentplan',
            name='zoning',
            field=models.CharField(blank=True, max_length=34, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldevelopmentplan',
            name='acreage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldevelopmentplan',
            name='appealperi',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldevelopmentplan',
            name='approved',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldevelopmentplan',
            name='cac',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldevelopmentplan',
            name='creationda',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldevelopmentplan',
            name='creator',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldevelopmentplan',
            name='daystoappr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldevelopmentplan',
            name='developer',
            field=models.CharField(blank=True, max_length=48, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldevelopmentplan',
            name='developer_field',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldevelopmentplan',
            name='devplan_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldevelopmentplan',
            name='editdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldevelopmentplan',
            name='editor',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldevelopmentplan',
            name='engineer',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldevelopmentplan',
            name='engineer_p',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldevelopmentplan',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='historicaldevelopmentplan',
            name='lots_apprv',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldevelopmentplan',
            name='lots_rec',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldevelopmentplan',
            name='lots_req',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldevelopmentplan',
            name='major_stre',
            field=models.CharField(blank=True, max_length=31, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldevelopmentplan',
            name='plan_name',
            field=models.CharField(blank=True, max_length=44, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldevelopmentplan',
            name='plan_numbe',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldevelopmentplan',
            name='plan_type',
            field=models.CharField(blank=True, max_length=39, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldevelopmentplan',
            name='planner',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldevelopmentplan',
            name='planurl',
            field=models.CharField(blank=True, max_length=107, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldevelopmentplan',
            name='planurl_ap',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldevelopmentplan',
            name='sq_ft_req',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldevelopmentplan',
            name='status',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldevelopmentplan',
            name='submitted',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldevelopmentplan',
            name='submitted_field',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldevelopmentplan',
            name='sunset_dat',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldevelopmentplan',
            name='units_appr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldevelopmentplan',
            name='units_req',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldevelopmentplan',
            name='updated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldevelopmentplan',
            name='zoning',
            field=models.CharField(blank=True, max_length=34, null=True),
        ),
    ]
